DROP TABLE IF EXISTS post;

CREATE TABLE IF NOT EXISTS post (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),  -- database column in snake_case
    title VARCHAR(255),
    content VARCHAR(255)
);

INSERT INTO post (created_by, title, content) VALUES 
('admin', 'Mastering Java in 2025', 'Java remains one of the most powerful and versatile programming languages, ideal for building scalable backend systems, Android apps, and enterprise software in today’s tech-driven world.'),
('user', 'Why Python Dominates Data Science', 'Python is the top choice for data science, machine learning, and automation due to its simplicity, extensive libraries, and supportive community.');
