-- Drop the table if it exists
DROP TABLE IF EXISTS post;

-- Create table statement
CREATE TABLE IF NOT EXISTS post (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    content VARCHAR(255)
);

-- Insert data into the table
INSERT INTO post (title, content) VALUES 
('Mastering Java in 2025', 'Java remains one of the most powerful and versatile programming languages, ideal for building scalable backend systems, Android apps, and enterprise software in today’s tech-driven world.'),
('Why Python Dominates Data Science', 'Python is the top choice for data science, machine learning, and automation due to its simplicity, extensive libraries, and supportive community.');
